### PR TITLE
Inria Chile - ITC2018

### PR DESCRIPTION
**Pull request by celbertin**
I have created some small edits and additions to the readme file from our experience replicating this project, which may be useful to others who wish to replicate it in the future. There is also the addition of the Poppy Torso support piece which can be 3D printed, and some small changes to adapt the torso to this setup.

### CODE REVIEW

**Comment by show0k** [comment]
Thanks a lot for these feedbacks and corrections!
The modified torso support is not on the PR, is it normal ?

**Comment by celbertin** [comment]
No problem!
The modified torso support should be in hardware/support/support.md as a link to an OnShape piece, can you see it on your end?

**Comment by show0k** [comment]
Oups, I didn't see the link. Perfect !

**Comment by sebastien-forestier** [comment]
Thanks a lot for your contribution !

**Pull request merged**
